"""Constants for Alexa Assist Bridge."""

DOMAIN = "alexa_assist_bridge"

CONF_ALEXA_SKILL_ID = "alexa_skill_id"
CONF_ALLOW_DEBUG_REQUESTS = "allow_debug_requests"
CONF_AGENT_ID = "agent_id"
CONF_ASSISTANT_NAME = "assistant_name"
CONF_CONVERSATION_MODE = "conversation_mode"
CONF_ENDPOINT_ID = "endpoint_id"
CONF_LANGUAGE = "language"
CONF_SPOKEN_RESPONSE_PROMPT = "spoken_response_prompt"

DEFAULT_AGENT_ID = "conversation.home_assistant"
DEFAULT_ASSISTANT_NAME = "Nabu"
DEFAULT_LANGUAGE = "en"
DEFAULT_ALLOW_DEBUG_REQUESTS = True
DEFAULT_CONVERSATION_MODE = "assist"
DEFAULT_SPOKEN_RESPONSE_PROMPT = True

CONVERSATION_MODE_ASSIST = "assist"
CONVERSATION_MODE_ALWAYS = "always"
CONVERSATION_MODE_NEVER = "never"
CONVERSATION_MODES = [
    CONVERSATION_MODE_ASSIST,
    CONVERSATION_MODE_ALWAYS,
    CONVERSATION_MODE_NEVER,
]

SIGNAL_DIAGNOSTICS_UPDATED = f"{DOMAIN}_diagnostics_updated"
